package com.padym.rusread.viewmodels
import com.padym.rusread.R

data class Syllable(
    val key: String,
    val resId: Int = 0,
    val millisOffset: Int = Int.MAX_VALUE
) {
    companion object {

        private val consonantGroups = listOf(
            listOf("б", "в", "г", "д", "з"),
            listOf("к", "л", "м", "н"),
            listOf("п", "р", "с", "т"),
            listOf("л", "м", "н", "р"),
            listOf("б", "п"),
            listOf("в", "ф"),
            listOf("г", "к"),
            listOf("д", "т"),
        )
        private val vowelGroups = listOf(
            listOf("а", "о", "у", "ы", "э"),
            listOf("е", "ё", "и", "ю", "я")
        )

        fun findOffset(syllable: String): Int {
            return getAll().find { it.key == syllable }?.millisOffset ?: 0
        }

        fun findResourceId(syllable: String): Int {
            return getAll().find { it.key == syllable }?.resId ?: 0
        }


        fun getFirstTimeGroup() = setOf("ма", "мо", "му", "па", "по", "пу")

        fun getPreselectedGroups() = buildNormalGroups() +
                getSingleLetterGroups() +
                getHissConsonantGroups() +
                getSoftSignGroups()

        private fun buildNormalGroups(): List<List<String>> {
            return vowelGroups.flatMap { vowels ->
                consonantGroups.map { consonants ->
                    consonants.flatMap { consonant ->
                        vowels.map { vowel -> consonant + vowel }
                    }
                }
            }
        }

        private fun getSingleLetterGroups() = listOf(
            listOf("а", "е", "ё", "и", "о", "у", "ы", "э", "ю", "я"),
            listOf("б", "в", "г", "д", "ж", "з", "й", "к", "л", "м", "н"),
            listOf("п", "р", "с", "т", "ф", "х", "ц", "ч", "ш", "щ")
        )

        private fun getHissConsonantGroups() = listOf(
            listOf(
                "жа", "жо", "жу", "хэ",
                "ха", "хо", "ху", "хы", "хэ",
                "ца", "цо", "цу", "цы", "цэ",
                "ча", "чо", "чу",
                "ша", "шо", "шу",
                "ща", "що", "щу"
            ),
            listOf(
                "же", "жё", "жи",
                "хе", "хё", "хи", "хю", "хя",
                "це", "ци",
                "че", "чё", "чи",
                "ше", "шё", "ши",
                "ще", "щё", "щи",
            )
        )

        private fun getSoftSignGroups() = listOf(
            listOf("б", "в", "г", "д", "бь", "вь", "гь", "дь"),
            listOf("к", "л", "м", "н", "кь", "ль", "мь", "нь"),
            listOf("п", "р", "с", "т", "пь", "рь", "сь", "ть"),
            listOf("з", "зь", "ж", "жь", "ч", "чь", "ш", "шь", "щ", "щь"),
        )

        fun getAll(): List<Syllable> = listOf(
            Syllable("а", resId = R.raw.a01_1_a),
            Syllable("е", resId = R.raw.a11_1_e),
            Syllable("ё", resId = R.raw.a06_1_jo),
            Syllable("и", resId = R.raw.a09_1_i),
            Syllable("о", resId = R.raw.a16_1_o),
            Syllable("у", resId = R.raw.a21_1_u),
            Syllable("ы", millisOffset = 7300),
            Syllable("э", millisOffset = 8200),
            Syllable("ю", millisOffset = 9200),
            Syllable("я", millisOffset = 10500),
            Syllable("б", resId = R.raw.a02_1_b),
            Syllable("бь", resId = R.raw.a02_9_b_soft),
            Syllable("ба", resId = R.raw.a02_2_ba),
            Syllable("бе", resId = R.raw.a02_3_be),
            Syllable("бё", resId = R.raw.a02_4_bjo),
            Syllable("би", resId = R.raw.a02_5_bi),
            Syllable("бо", resId = R.raw.a02_6_bo),
            Syllable("бу", resId = R.raw.a02_7_bu),
            Syllable("бы", resId = R.raw.a02_8_by),
            Syllable("бэ", resId = R.raw.a02_10_bee),
            Syllable("бю", resId = R.raw.a02_11_bju),
            Syllable("бя", resId = R.raw.a02_12_bja),
            Syllable("в", resId = R.raw.a03_1_v),
            Syllable("вь", resId = R.raw.a03_9_v_soft),
            Syllable("ва", resId = R.raw.a03_2_va),
            Syllable("ве", resId = R.raw.a03_3_ve),
            Syllable("вё", resId = R.raw.a03_4_vjo),
            Syllable("ви", resId = R.raw.a03_5_vi),
            Syllable("во", resId = R.raw.a03_6_vo),
            Syllable("ву", resId = R.raw.a03_7_vu),
            Syllable("вы", resId = R.raw.a03_8_vy),
            Syllable("вэ", resId = R.raw.a03_10_vee),
            Syllable("вю", resId = R.raw.a03_11_vju),
            Syllable("вя", resId = R.raw.a03_12_vja),
            Syllable("г", resId = R.raw.a04_1_g),
            Syllable("гь", resId = R.raw.a04_9_g_soft),
            Syllable("га", resId = R.raw.a04_2_ga),
            Syllable("ге", resId = R.raw.a04_3_ge),
            Syllable("гё", resId = R.raw.a04_4_gjo),
            Syllable("ги", resId = R.raw.a04_5_gi),
            Syllable("го", resId = R.raw.a04_6_go),
            Syllable("гу", resId = R.raw.a04_7_gu),
            Syllable("гы", resId = R.raw.a04_8_gy),
            Syllable("гэ", resId = R.raw.a04_10_gee),
            Syllable("гю", resId = R.raw.a04_11_gju),
            Syllable("гя", resId = R.raw.a04_12_gja),
            Syllable("д", resId = R.raw.a05_1_d),
            Syllable("дь", resId = R.raw.a05_9_d_soft),
            Syllable("да", resId = R.raw.a05_2_da),
            Syllable("де", resId = R.raw.a05_3_de),
            Syllable("дё", resId = R.raw.a05_4_djo),
            Syllable("ди", resId = R.raw.a05_5_di),
            Syllable("до", resId = R.raw.a05_6_do),
            Syllable("ду", resId = R.raw.a05_7_du),
            Syllable("ды", resId = R.raw.a05_8_dy),
            Syllable("дэ", resId = R.raw.a05_10_dee),
            Syllable("дю", resId = R.raw.a05_11_dju),
            Syllable("дя", resId = R.raw.a05_12_dja),
            Syllable("ж", resId = R.raw.a07_1_jj),
            Syllable("жь", resId = R.raw.a07_1_jj),
            Syllable("жа", resId = R.raw.a07_2_jja),
            Syllable("же", resId = R.raw.a07_6_jjee),
            Syllable("жё", resId = R.raw.a07_4_jo),
            Syllable("жи", resId = R.raw.a07_3_jji),
            Syllable("жо", resId = R.raw.a07_4_jo),
            Syllable("жу", resId = R.raw.a07_5_jju),
            Syllable("жы", resId = R.raw.a07_3_jji),
            Syllable("жэ", resId = R.raw.a07_6_jjee),
            Syllable("жю", resId = R.raw.a07_5_jju),
            Syllable("жя"),
            Syllable("з", resId = R.raw.a08_1_z),
            Syllable("зь", resId = R.raw.a08_9_z_soft),
            Syllable("за", resId = R.raw.a08_2_za),
            Syllable("зе", resId = R.raw.a08_3_ze),
            Syllable("зё", resId = R.raw.a08_4_zjo),
            Syllable("зи", resId = R.raw.a08_5_zi),
            Syllable("зо", resId = R.raw.a08_6_zo),
            Syllable("зу", resId = R.raw.a08_7_zu),
            Syllable("зы", resId = R.raw.a08_8_zy),
            Syllable("зэ", resId = R.raw.a08_10_zee),
            Syllable("зю", resId = R.raw.a08_11_zju),
            Syllable("зя", resId = R.raw.a08_12_zja),
            Syllable("й", resId = R.raw.a10_1_j),
            Syllable("к", resId = R.raw.a12_1_k),
            Syllable("кь", resId = R.raw.a12_9_k_soft),
            Syllable("ка", resId = R.raw.a12_2_ka),
            Syllable("ке", resId = R.raw.a12_3_ke),
            Syllable("кё", resId = R.raw.a12_4_kjo),
            Syllable("ки", resId = R.raw.a12_5_ki),
            Syllable("ко", resId = R.raw.a12_6_ko),
            Syllable("ку", resId = R.raw.a12_7_ku),
            Syllable("кы", resId = R.raw.a12_8_ky),
            Syllable("кэ", resId = R.raw.a12_10_kee),
            Syllable("кю", resId = R.raw.a12_11_kju),
            Syllable("кя", resId = R.raw.a12_12_kja),
            Syllable("л", resId = R.raw.a13_1_l),
            Syllable("ль", resId = R.raw.a13_9_l_soft),
            Syllable("ла", resId = R.raw.a13_2_la),
            Syllable("ле", resId = R.raw.a13_3_le),
            Syllable("лё", resId = R.raw.a13_4_ljo),
            Syllable("ли", resId = R.raw.a13_5_li),
            Syllable("ло", resId = R.raw.a13_6_lo),
            Syllable("лу", resId = R.raw.a13_7_lu),
            Syllable("лы", resId = R.raw.a13_8_ly),
            Syllable("лэ", resId = R.raw.a13_10_lee),
            Syllable("лю", resId = R.raw.a13_11_lju),
            Syllable("ля", resId = R.raw.a13_13_lja),
            Syllable("м", resId = R.raw.a14_1_m),
            Syllable("ма", resId = R.raw.a14_2_ma),
            Syllable("ме", resId = R.raw.a14_3_me),
            Syllable("мё", resId = R.raw.a14_4_mjo),
            Syllable("ми", resId = R.raw.a14_5_mi),
            Syllable("мо", resId = R.raw.a14_6_mo),
            Syllable("му", resId = R.raw.a14_7_mu),
            Syllable("мы", resId = R.raw.a14_8_my),
            Syllable("мь", resId = R.raw.a14_9_m_soft),
            Syllable("мэ", resId = R.raw.a14_10_mee),
            Syllable("мю", resId = R.raw.a14_11_mju),
            Syllable("мя", resId = R.raw.a14_12_mja),
            Syllable("н", resId = R.raw.a15_1_n),
            Syllable("на", resId = R.raw.a15_2_na),
            Syllable("не", resId = R.raw.a15_3_ne),
            Syllable("нё", resId = R.raw.a15_4_njo),
            Syllable("ни", resId = R.raw.a15_5_ni),
            Syllable("но", resId = R.raw.a15_6_no),
            Syllable("ну", resId = R.raw.a15_7_nu),
            Syllable("ны", resId = R.raw.a15_8_ny),
            Syllable("нь", resId = R.raw.a15_9_n_soft),
            Syllable("нэ", resId = R.raw.a15_10_nee),
            Syllable("ню", resId = R.raw.a15_11_nju),
            Syllable("ня", resId = R.raw.a15_12_nja),
            Syllable("п", resId = R.raw.a17_1_p),
            Syllable("па", resId = R.raw.a17_2_pa),
            Syllable("пе", resId = R.raw.a17_3_pe),
            Syllable("пё", resId = R.raw.a17_4_pjo),
            Syllable("пи", resId = R.raw.a17_5_pi),
            Syllable("по", resId = R.raw.a17_6_po),
            Syllable("пу", resId = R.raw.a17_7_pu),
            Syllable("пы", resId = R.raw.a17_8_py),
            Syllable("пь", resId = R.raw.a17_9_p_soft),
            Syllable("пэ", resId = R.raw.a17_10_pee),
            Syllable("пю", resId = R.raw.a17_11_pju),
            Syllable("пя", resId = R.raw.a17_12_pja),
            Syllable("р", resId = R.raw.a18_1_r),
            Syllable("ра", resId = R.raw.a18_2_ra),
            Syllable("ре", resId = R.raw.a18_3_re),
            Syllable("рё", resId = R.raw.a18_4_rjo),
            Syllable("ри", resId = R.raw.a18_5_ri),
            Syllable("ро", resId = R.raw.a18_6_ro),
            Syllable("ру", resId = R.raw.a18_7_ru),
            Syllable("ры", resId = R.raw.a18_8_ry),
            Syllable("рь", resId = R.raw.a18_9_r_soft),
            Syllable("рэ", resId = R.raw.a18_10_ree),
            Syllable("рю", resId = R.raw.a18_11_rju),
            Syllable("ря", resId = R.raw.a18_12_rja),
            Syllable("с", resId = R.raw.a19_1_s),
            Syllable("са", resId = R.raw.a19_2_sa),
            Syllable("се", resId = R.raw.a19_3_se),
            Syllable("сё", resId = R.raw.a19_4_sjo),
            Syllable("си", resId = R.raw.a19_5_si),
            Syllable("со", resId = R.raw.a19_6_so),
            Syllable("су", resId = R.raw.a19_7_su),
            Syllable("сы", resId = R.raw.a19_8_sy),
            Syllable("сь", resId = R.raw.a19_9_s_soft),
            Syllable("сэ", resId = R.raw.a19_10_see),
            Syllable("сю", resId = R.raw.a19_11_sju),
            Syllable("ся", resId = R.raw.a19_12_sja),
            Syllable("т", resId = R.raw.a20_1_t),
            Syllable("та", resId = R.raw.a20_2_ta),
            Syllable("те", resId = R.raw.a20_3_te),
            Syllable("тё", resId = R.raw.a20_4_tjo),
            Syllable("ти", resId = R.raw.a20_5_ti),
            Syllable("то", resId = R.raw.a20_6_to),
            Syllable("ту", resId = R.raw.a20_7_tu),
            Syllable("ты", resId = R.raw.a20_8_ty),
            Syllable("ть", resId = R.raw.a20_9_t_soft),
            Syllable("тэ", resId = R.raw.a20_10_tee),
            Syllable("тю", resId = R.raw.a20_11_tju),
            Syllable("тя", resId = R.raw.a20_12_tja),
            Syllable("ф", resId = R.raw.a22_1_f),
            Syllable("фа", resId = R.raw.a22_2_fa),
            Syllable("фе", resId = R.raw.a22_3_fe),
            Syllable("фё", resId = R.raw.a22_4_fjo),
            Syllable("фи", resId = R.raw.a22_5_fi),
            Syllable("фо", resId = R.raw.a22_6_fo),
            Syllable("фу", resId = R.raw.a22_7_fu),
            Syllable("фы", resId = R.raw.a22_8_fy),
            Syllable("фь", resId = R.raw.a22_9_f_soft),
            Syllable("фэ", resId = R.raw.a22_10_fee),
            Syllable("фю", resId = R.raw.a22_11_fju),
            Syllable("фя", resId = R.raw.a22_12_fja),
            Syllable("х", resId = R.raw.a23_1_h),
            Syllable("ха", resId = R.raw.a23_2_ha),
            Syllable("хе", resId = R.raw.a23_3_he),
            Syllable("хё", resId = R.raw.a23_4_hjo),
            Syllable("хи", resId = R.raw.a23_5_hi),
            Syllable("хо", resId = R.raw.a23_6_ho),
            Syllable("ху", resId = R.raw.a23_7_hu),
            Syllable("хы", resId = R.raw.a23_8_hy),
            Syllable("хь", resId = R.raw.a23_9_h_soft),
            Syllable("хэ", resId = R.raw.a23_10_hee),
            Syllable("хю", resId = R.raw.a23_11_hju),
            Syllable("хя", resId = R.raw.a23_12_hja),
            Syllable("ц", millisOffset = 250200),
            Syllable("ць"),
            Syllable("ца", millisOffset = 251000),
            Syllable("це", millisOffset = 255000),
            Syllable("цё"),
            Syllable("ци", millisOffset = 254000),
            Syllable("цо", millisOffset = 251800),
            Syllable("цу", millisOffset = 252800),
            Syllable("цы", millisOffset = 254000),
            Syllable("цэ", millisOffset = 255000),
            Syllable("цю"),
            Syllable("ця"),
            Syllable("ч", millisOffset = 255600),
            Syllable("чь", millisOffset = 255600),
            Syllable("ча", millisOffset = 263600),
            Syllable("че", millisOffset = 257000),
            Syllable("чё", millisOffset = 259000),
            Syllable("чи", millisOffset = 260700),
            Syllable("чо", millisOffset = 259000),
            Syllable("чу", millisOffset = 262300),
            Syllable("чы"),
            Syllable("чэ"),
            Syllable("чю", millisOffset = 262300),
            Syllable("чя", millisOffset = 263600),
            Syllable("ш", millisOffset = 264500),
            Syllable("шь", millisOffset = 264500),
            Syllable("ша", millisOffset = 265700),
            Syllable("ше", millisOffset = 271500),
            Syllable("шё", millisOffset = 267500),
            Syllable("ши", millisOffset = 270200),
            Syllable("шо", millisOffset = 267500),
            Syllable("шу", millisOffset = 268800),
            Syllable("шы", millisOffset = 270200),
            Syllable("шэ", millisOffset = 271500),
            Syllable("шю", millisOffset = 268800),
            Syllable("шя"),
            Syllable("щ", millisOffset = 272600),
            Syllable("щь", millisOffset = 272600),
            Syllable("ща", millisOffset = 280000),
            Syllable("ще", millisOffset = 274000),
            Syllable("щё", millisOffset = 275700),
            Syllable("щи", millisOffset = 277000),
            Syllable("що"),
            Syllable("щу", millisOffset = 278500),
            Syllable("щы"),
            Syllable("щэ"),
            Syllable("щю", millisOffset = 278500),
            Syllable("щя", millisOffset = 280000),
            Syllable("ь", millisOffset = 281800),
            Syllable("ъ", millisOffset = 283000)
        )
    }
}