package com.padym.rusread.viewmodels
import com.padym.rusread.R

data class Syllable(
    val key: String,
    val resId: Int = 0,
    val millisOffset: Int = Int.MAX_VALUE
) {
    companion object {

        private val consonantGroups = listOf(
            listOf("б", "в", "г", "д", "з"),
            listOf("к", "л", "м", "н"),
            listOf("п", "р", "с", "т"),
            listOf("л", "м", "н", "р"),
            listOf("б", "п"),
            listOf("в", "ф"),
            listOf("г", "к"),
            listOf("д", "т"),
        )
        private val vowelGroups = listOf(
            listOf("а", "о", "у", "ы", "э"),
            listOf("е", "ё", "и", "ю", "я")
        )

        fun findOffset(syllable: String): Int {
            return getAll().find { it.key == syllable }?.millisOffset ?: 0
        }

        fun findResourceId(syllable: String): Int {
            return getAll().find { it.key == syllable }?.resId ?: 0
        }


        fun getFirstTimeGroup() = setOf("ма", "мо", "му", "па", "по", "пу")

        fun getPreselectedGroups() = buildNormalGroups() +
                getSingleLetterGroups() +
                getHissConsonantGroups() +
                getSoftSignGroups()

        private fun buildNormalGroups(): List<List<String>> {
            return vowelGroups.flatMap { vowels ->
                consonantGroups.map { consonants ->
                    consonants.flatMap { consonant ->
                        vowels.map { vowel -> consonant + vowel }
                    }
                }
            }
        }

        private fun getSingleLetterGroups() = listOf(
            listOf("а", "е", "ё", "и", "о", "у", "ы", "э", "ю", "я"),
            listOf("б", "в", "г", "д", "ж", "з", "й", "к", "л", "м", "н"),
            listOf("п", "р", "с", "т", "ф", "х", "ц", "ч", "ш", "щ")
        )

        private fun getHissConsonantGroups() = listOf(
            listOf(
                "жа", "жо", "жу", "хэ",
                "ха", "хо", "ху", "хы", "хэ",
                "ца", "цо", "цу", "цы", "цэ",
                "ча", "чо", "чу",
                "ша", "шо", "шу",
                "ща", "що", "щу"
            ),
            listOf(
                "же", "жё", "жи",
                "хе", "хё", "хи", "хю", "хя",
                "це", "ци",
                "че", "чё", "чи",
                "ше", "шё", "ши",
                "ще", "щё", "щи",
            )
        )

        private fun getSoftSignGroups() = listOf(
            listOf("б", "в", "г", "д", "бь", "вь", "гь", "дь"),
            listOf("к", "л", "м", "н", "кь", "ль", "мь", "нь"),
            listOf("п", "р", "с", "т", "пь", "рь", "сь", "ть"),
            listOf("з", "зь", "ж", "жь", "ч", "чь", "ш", "шь", "щ", "щь"),
        )

        fun getAll(): List<Syllable> = listOf(
            Syllable("а", resId = R.raw.a01_1_a),
            Syllable("е", millisOffset = 1000),
            Syllable("ё", millisOffset = 2000),
            Syllable("и", millisOffset = 3000),
            Syllable("о", millisOffset = 4000),
            Syllable("у", millisOffset = 5300),
            Syllable("ы", millisOffset = 7300),
            Syllable("э", millisOffset = 8200),
            Syllable("ю", millisOffset = 9200),
            Syllable("я", millisOffset = 10500),
            Syllable("б", resId = R.raw.a02_1_b),
            Syllable("бь", resId = R.raw.a02_9_b_soft),
            Syllable("ба", resId = R.raw.a02_2_ba),
            Syllable("бе", resId = R.raw.a02_3_be),
            Syllable("бё", resId = R.raw.a02_4_bjo),
            Syllable("би", resId = R.raw.a02_5_bi),
            Syllable("бо", resId = R.raw.a02_6_bo),
            Syllable("бу", resId = R.raw.a02_7_bu),
            Syllable("бы", resId = R.raw.a02_8_by),
            Syllable("бэ", resId = R.raw.a02_10_bee),
            Syllable("бю", resId = R.raw.a02_11_bju),
            Syllable("бя", resId = R.raw.a02_12_bja),
            Syllable("в", resId = R.raw.a03_1_v),
            Syllable("вь", resId = R.raw.a03_9_v_soft),
            Syllable("ва", resId = R.raw.a03_2_va),
            Syllable("ве", resId = R.raw.a03_3_ve),
            Syllable("вё", resId = R.raw.a03_4_vjo),
            Syllable("ви", resId = R.raw.a03_5_vi),
            Syllable("во", resId = R.raw.a03_6_vo),
            Syllable("ву", resId = R.raw.a03_7_vu),
            Syllable("вы", resId = R.raw.a03_8_vy),
            Syllable("вэ", resId = R.raw.a03_10_vee),
            Syllable("вю", resId = R.raw.a03_11_vju),
            Syllable("вя", resId = R.raw.a03_12_vja),
            Syllable("г", millisOffset = 40800),
            Syllable("гь", millisOffset = 41800),
            Syllable("га", millisOffset = 42800),
            Syllable("ге", millisOffset = 44000),
            Syllable("гё", millisOffset = 46000),
            Syllable("ги", millisOffset = 47700),
            Syllable("го", millisOffset = 49300),
            Syllable("гу", millisOffset = 50600),
            Syllable("гы", millisOffset = 52000),
            Syllable("гэ", millisOffset = 53900),
            Syllable("гю", millisOffset = 55000),
            Syllable("гя", millisOffset = 56600),
            Syllable("д", millisOffset = 58000),
            Syllable("дь", millisOffset = 58800),
            Syllable("да", millisOffset = 59800),
            Syllable("де", millisOffset = 61000),
            Syllable("дё", millisOffset = 62700),
            Syllable("ди", millisOffset = 64000),
            Syllable("до", millisOffset = 65500),
            Syllable("ду", millisOffset = 67000),
            Syllable("ды", millisOffset = 68800),
            Syllable("дэ", millisOffset = 70000),
            Syllable("дю", millisOffset = 71300),
            Syllable("дя", millisOffset = 72800),
            Syllable("ж", millisOffset = 74000),
            Syllable("жь", millisOffset = 74000),
            Syllable("жа", millisOffset = 75300),
            Syllable("же", millisOffset = 79200),
            Syllable("жё", millisOffset = 76500),
            Syllable("жи", millisOffset = 78200),
            Syllable("жо", millisOffset = 76500),
            Syllable("жу", millisOffset = 77500),
            Syllable("жы", millisOffset = 78200),
            Syllable("жэ", millisOffset = 79200),
            Syllable("жю", millisOffset = 77500),
            Syllable("жя"),
            Syllable("з", millisOffset = 80300),
            Syllable("зь", millisOffset = 81500),
            Syllable("за", millisOffset = 82700),
            Syllable("зе", millisOffset = 84000),
            Syllable("зё", millisOffset = 85300),
            Syllable("зи", millisOffset = 87000),
            Syllable("зо", millisOffset = 88600),
            Syllable("зу", millisOffset = 90000),
            Syllable("зы", millisOffset = 90800),
            Syllable("зэ", millisOffset = 91800),
            Syllable("зю", millisOffset = 93000),
            Syllable("зя", millisOffset = 93800),
            Syllable("й", millisOffset = 95200),
            Syllable("к", millisOffset = 96200),
            Syllable("кь", millisOffset = 97300),
            Syllable("ка", millisOffset = 98200),
            Syllable("ке", millisOffset = 99000),
            Syllable("кё", millisOffset = 100000),
            Syllable("ки", millisOffset = 102000),
            Syllable("ко", millisOffset = 103700),
            Syllable("ку", millisOffset = 105500),
            Syllable("кы", millisOffset = 107000),
            Syllable("кэ", millisOffset = 108200),
            Syllable("кю", millisOffset = 109500),
            Syllable("кя", millisOffset = 110700),
            Syllable("л", millisOffset = 111600),
            Syllable("ль", millisOffset = 112400),
            Syllable("ла", millisOffset = 113300),
            Syllable("ле", millisOffset = 114300),
            Syllable("лё", millisOffset = 115600),
            Syllable("ли", millisOffset = 116800),
            Syllable("ло", millisOffset = 118000),
            Syllable("лу", millisOffset = 119500),
            Syllable("лы", millisOffset = 120300),
            Syllable("лэ", millisOffset = 121100),
            Syllable("лю", millisOffset = 122000),
            Syllable("ля", millisOffset = 123000),
            Syllable("м", millisOffset = 124300),
            Syllable("мь", millisOffset = 125300),
            Syllable("ма", millisOffset = 126200),
            Syllable("ме", millisOffset = 127200),
            Syllable("мё", millisOffset = 128000),
            Syllable("ми", millisOffset = 129000),
            Syllable("мо", millisOffset = 130200),
            Syllable("му", millisOffset = 132000),
            Syllable("мы", millisOffset = 133700),
            Syllable("мэ", millisOffset = 135000),
            Syllable("мю", millisOffset = 136500),
            Syllable("мя", millisOffset = 138000),
            Syllable("н", millisOffset = 139200),
            Syllable("нь", millisOffset = 140200),
            Syllable("на", millisOffset = 141000),
            Syllable("не", millisOffset = 142500),
            Syllable("нё", millisOffset = 144200),
            Syllable("ни", millisOffset = 145300),
            Syllable("но", millisOffset = 146700),
            Syllable("ну", millisOffset = 148000),
            Syllable("ны", millisOffset = 149500),
            Syllable("нэ", millisOffset = 150800),
            Syllable("ню", millisOffset = 152700),
            Syllable("ня", millisOffset = 154200),
            Syllable("п", millisOffset = 155200),
            Syllable("пь", millisOffset = 156200),
            Syllable("па", millisOffset = 157500),
            Syllable("пе", millisOffset = 159200),
            Syllable("пё", millisOffset = 160600),
            Syllable("пи", millisOffset = 161800),
            Syllable("по", millisOffset = 163100),
            Syllable("пу", millisOffset = 164500),
            Syllable("пы", millisOffset = 166200),
            Syllable("пэ", millisOffset = 167200),
            Syllable("пю", millisOffset = 168800),
            Syllable("пя", millisOffset = 169800),
            Syllable("р", millisOffset = 171200),
            Syllable("рь", millisOffset = 172200),
            Syllable("ра", millisOffset = 173500),
            Syllable("ре", millisOffset = 175300),
            Syllable("рё", millisOffset = 177000),
            Syllable("ри", millisOffset = 178200),
            Syllable("ро", millisOffset = 179500),
            Syllable("ру", millisOffset = 181000),
            Syllable("ры", millisOffset = 182300),
            Syllable("рэ", millisOffset = 183500),
            Syllable("рю", millisOffset = 185000),
            Syllable("ря", millisOffset = 186500),
            Syllable("с", millisOffset = 188500),
            Syllable("сь", millisOffset = 189500),
            Syllable("са", millisOffset = 190800),
            Syllable("се", millisOffset = 192000),
            Syllable("сё", millisOffset = 193000),
            Syllable("си", millisOffset = 194000),
            Syllable("со", millisOffset = 195700),
            Syllable("су", millisOffset = 197000),
            Syllable("сы", millisOffset = 197800),
            Syllable("сэ", millisOffset = 198700),
            Syllable("сю", millisOffset = 199500),
            Syllable("ся", millisOffset = 200300),
            Syllable("т", millisOffset = 201200),
            Syllable("ть", millisOffset = 202200),
            Syllable("та", millisOffset = 203200),
            Syllable("те", millisOffset = 205200),
            Syllable("тё", millisOffset = 206500),
            Syllable("ти", millisOffset = 207500),
            Syllable("то", millisOffset = 209000),
            Syllable("ту", millisOffset = 210700),
            Syllable("ты", millisOffset = 212000),
            Syllable("тэ", millisOffset = 213500),
            Syllable("тю", millisOffset = 215300),
            Syllable("тя", millisOffset = 216800),
            Syllable("ф", millisOffset = 217700),
            Syllable("фь", millisOffset = 218500),
            Syllable("фа", millisOffset = 219700),
            Syllable("фе", millisOffset = 221000),
            Syllable("фё", millisOffset = 222300),
            Syllable("фи", millisOffset = 224000),
            Syllable("фо", millisOffset = 225500),
            Syllable("фу", millisOffset = 227000),
            Syllable("фы", millisOffset = 228400),
            Syllable("фэ", millisOffset = 229800),
            Syllable("фю", millisOffset = 230500),
            Syllable("фя", millisOffset = 232500),
            Syllable("х", millisOffset = 233500),
            Syllable("хь", millisOffset = 234200),
            Syllable("ха", millisOffset = 235000),
            Syllable("хе", millisOffset = 236100),
            Syllable("хё", millisOffset = 238000),
            Syllable("хи", millisOffset = 239500),
            Syllable("хо", millisOffset = 240600),
            Syllable("ху", millisOffset = 242000),
            Syllable("хы", millisOffset = 243800),
            Syllable("хэ", millisOffset = 245700),
            Syllable("хю", millisOffset = 247500),
            Syllable("хя", millisOffset = 248800),
            Syllable("ц", millisOffset = 250200),
            Syllable("ць"),
            Syllable("ца", millisOffset = 251000),
            Syllable("це", millisOffset = 255000),
            Syllable("цё"),
            Syllable("ци", millisOffset = 254000),
            Syllable("цо", millisOffset = 251800),
            Syllable("цу", millisOffset = 252800),
            Syllable("цы", millisOffset = 254000),
            Syllable("цэ", millisOffset = 255000),
            Syllable("цю"),
            Syllable("ця"),
            Syllable("ч", millisOffset = 255600),
            Syllable("чь", millisOffset = 255600),
            Syllable("ча", millisOffset = 263600),
            Syllable("че", millisOffset = 257000),
            Syllable("чё", millisOffset = 259000),
            Syllable("чи", millisOffset = 260700),
            Syllable("чо", millisOffset = 259000),
            Syllable("чу", millisOffset = 262300),
            Syllable("чы"),
            Syllable("чэ"),
            Syllable("чю", millisOffset = 262300),
            Syllable("чя", millisOffset = 263600),
            Syllable("ш", millisOffset = 264500),
            Syllable("шь", millisOffset = 264500),
            Syllable("ша", millisOffset = 265700),
            Syllable("ше", millisOffset = 271500),
            Syllable("шё", millisOffset = 267500),
            Syllable("ши", millisOffset = 270200),
            Syllable("шо", millisOffset = 267500),
            Syllable("шу", millisOffset = 268800),
            Syllable("шы", millisOffset = 270200),
            Syllable("шэ", millisOffset = 271500),
            Syllable("шю", millisOffset = 268800),
            Syllable("шя"),
            Syllable("щ", millisOffset = 272600),
            Syllable("щь", millisOffset = 272600),
            Syllable("ща", millisOffset = 280000),
            Syllable("ще", millisOffset = 274000),
            Syllable("щё", millisOffset = 275700),
            Syllable("щи", millisOffset = 277000),
            Syllable("що"),
            Syllable("щу", millisOffset = 278500),
            Syllable("щы"),
            Syllable("щэ"),
            Syllable("щю", millisOffset = 278500),
            Syllable("щя", millisOffset = 280000),
            Syllable("ь", millisOffset = 281800),
            Syllable("ъ", millisOffset = 283000)
        )
    }
}