package com.padym.rusread.viewmodels

data class Syllable(
    val key: String,
    val ipa: String = "",
    val occurrenceCount: Int = 0
)

fun getSyllables(): List<Syllable> = listOf(
    Syllable("ба", occurrenceCount = 21),
    Syllable("бе", occurrenceCount = 29),
    Syllable("би", occurrenceCount = 27),
    Syllable("бо", occurrenceCount = 30),
    Syllable("бу", occurrenceCount = 53),
    Syllable("бы", occurrenceCount = 60),
    Syllable("ва", occurrenceCount = 81),
    Syllable("ве", occurrenceCount = 65),
    Syllable("ви", occurrenceCount = 37),
    Syllable("во", occurrenceCount = 82),
    Syllable("вы", occurrenceCount = 32),
    Syllable("га", occurrenceCount = 11),
    Syllable("ги", occurrenceCount = 12),
    Syllable("го", occurrenceCount = 111),
    Syllable("гу", occurrenceCount = 49),
    Syllable("да", occurrenceCount = 77),
    Syllable("де", occurrenceCount = 57),
    Syllable("ди", occurrenceCount = 34),
    Syllable("до", occurrenceCount = 52),
    Syllable("ду", occurrenceCount = 29),
    Syllable("дь", occurrenceCount = 20),
    Syllable("жа", occurrenceCount = 17),
    Syllable("же", occurrenceCount = 45),
    Syllable("жи", occurrenceCount = 17),
    Syllable("за", occurrenceCount = 69),
    Syllable("зо", occurrenceCount = 12),
    Syllable("зы", occurrenceCount = 27),
    Syllable("ка", occurrenceCount = 180),
    Syllable("ке", occurrenceCount = 12),
    Syllable("ки", occurrenceCount = 86),
    Syllable("ко", occurrenceCount = 128),
    Syllable("ку", occurrenceCount = 42),
    Syllable("ла", occurrenceCount = 51),
    Syllable("ле", occurrenceCount = 41),
    Syllable("ли", occurrenceCount = 131),
    Syllable("ло", occurrenceCount = 76),
    Syllable("лу", occurrenceCount = 30),
    Syllable("лы", occurrenceCount = 41),
    Syllable("ль", occurrenceCount = 55),
    Syllable("лю", occurrenceCount = 20),
    Syllable("ля", occurrenceCount = 38),
    Syllable("ма", occurrenceCount = 59),
    Syllable("ме", occurrenceCount = 52),
    Syllable("ми", occurrenceCount = 38),
    Syllable("мо", occurrenceCount = 45),
    Syllable("му", occurrenceCount = 54),
    Syllable("на", occurrenceCount = 231),
    Syllable("не", occurrenceCount = 195),
    Syllable("ни", occurrenceCount = 98),
    Syllable("но", occurrenceCount = 93),
    Syllable("ну", occurrenceCount = 36),
    Syllable("ны", occurrenceCount = 43),
    Syllable("нь", occurrenceCount = 51),
    Syllable("ня", occurrenceCount = 27),
    Syllable("па", occurrenceCount = 13),
    Syllable("пе", occurrenceCount = 15),
    Syllable("пи", occurrenceCount = 25),
    Syllable("по", occurrenceCount = 166),
    Syllable("пу", occurrenceCount = 17),
    Syllable("ра", occurrenceCount = 116),
    Syllable("ре", occurrenceCount = 82),
    Syllable("ри", occurrenceCount = 88),
    Syllable("ро", occurrenceCount = 100),
    Syllable("ру", occurrenceCount = 58),
    Syllable("ры", occurrenceCount = 12),
    Syllable("са", occurrenceCount = 25),
    Syllable("се", occurrenceCount = 58),
    Syllable("си", occurrenceCount = 38),
    Syllable("со", occurrenceCount = 89),
    Syllable("сь", occurrenceCount = 53),
    Syllable("ся", occurrenceCount = 82),
    Syllable("та", occurrenceCount = 73),
    Syllable("те", occurrenceCount = 79),
    Syllable("ти", occurrenceCount = 43),
    Syllable("то", occurrenceCount = 226),
    Syllable("ту", occurrenceCount = 20),
    Syllable("ты", occurrenceCount = 50),
    Syllable("ть", occurrenceCount = 96),
    Syllable("хо", occurrenceCount = 47),
    Syllable("ху", occurrenceCount = 13),
    Syllable("ца", occurrenceCount = 12),
    Syllable("це", occurrenceCount = 19),
    Syllable("ча", occurrenceCount = 28),
    Syllable("че", occurrenceCount = 51),
    Syllable("чи", occurrenceCount = 40),
    Syllable("ша", occurrenceCount = 17),
    Syllable("ше", occurrenceCount = 27),
    Syllable("ши", occurrenceCount = 31),
    Syllable("шь", occurrenceCount = 17),
    Syllable("щё", occurrenceCount = 12),
    Syllable("а"),
    Syllable("б"),
    Syllable("в"),
    Syllable("г"),
    Syllable("д"),
    Syllable("е"),
    Syllable("ж"),
    Syllable("з"),
    Syllable("и"),
    Syllable("й"),
    Syllable("к"),
    Syllable("л"),
    Syllable("м"),
    Syllable("н"),
    Syllable("о"),
    Syllable("п"),
    Syllable("р"),
    Syllable("с"),
    Syllable("т"),
    Syllable("у"),
    Syllable("х"),
    Syllable("ц"),
    Syllable("ч"),
    Syllable("ш"),
    Syllable("щ"),
    Syllable("э"),
    Syllable("ю"),
    Syllable("я"),
    Syllable("ё"),
)
