package com.padym.rusread

data class Syllable(
    val key: String,
    val ipa: String = "",
    val occurrenceCount: Int = 0
)

fun getSyllables(): List<Syllable> = listOf(
    Syllable("ба", "", 21),
    Syllable("бе", "", 29),
    Syllable("би", "", 27),
    Syllable("бо", "", 30),
    Syllable("бу", "", 53),
    Syllable("бы", "", 60),
    Syllable("ва", "", 81),
    Syllable("ве", "", 65),
    Syllable("ви", "", 37),
    Syllable("во", "", 82),
    Syllable("вы", "", 32),
    Syllable("га", "", 11),
    Syllable("ги", "", 12),
    Syllable("го", "", 111),
    Syllable("гу", "", 49),
    Syllable("да", "", 77),
    Syllable("де", "", 57),
    Syllable("ди", "", 34),
    Syllable("до", "", 52),
    Syllable("ду", "", 29),
    Syllable("дь", "", 20),
    Syllable("жа", "", 17),
    Syllable("же", "", 45),
    Syllable("жи", "", 17),
    Syllable("за", "", 69),
    Syllable("зо", "", 12),
    Syllable("зы", "", 27),
    Syllable("ка", "", 180),
    Syllable("ке", "", 12),
    Syllable("ки", "", 86),
    Syllable("ко", "", 128),
    Syllable("ку", "", 42),
    Syllable("ла", "", 51),
    Syllable("ле", "", 41),
    Syllable("ли", "", 131),
    Syllable("ло", "", 76),
    Syllable("лу", "", 30),
    Syllable("лы", "", 41),
    Syllable("ль", "", 55),
    Syllable("лю", "", 20),
    Syllable("ля", "", 38),
    Syllable("ма", "", 59),
    Syllable("ме", "", 52),
    Syllable("ми", "", 38),
    Syllable("мо", "", 45),
    Syllable("му", "", 54),
    Syllable("на", "", 231),
    Syllable("не", "", 195),
    Syllable("ни", "", 98),
    Syllable("но", "", 93),
    Syllable("ну", "", 36),
    Syllable("ны", "", 43),
    Syllable("нь", "", 51),
    Syllable("ня", "", 27),
    Syllable("па", "", 13),
    Syllable("пе", "", 15),
    Syllable("пи", "", 25),
    Syllable("по", "", 166),
    Syllable("пу", "", 17),
    Syllable("ра", "", 116),
    Syllable("ре", "", 82),
    Syllable("ри", "", 88),
    Syllable("ро", "", 100),
    Syllable("ру", "", 58),
    Syllable("ры", "", 12),
    Syllable("са", "", 25),
    Syllable("се", "", 58),
    Syllable("си", "", 38),
    Syllable("со", "", 89),
    Syllable("сь", "", 53),
    Syllable("ся", "", 82),
    Syllable("та", "", 73),
    Syllable("те", "", 79),
    Syllable("ти", "", 43),
    Syllable("то", "", 226),
    Syllable("ту", "", 20),
    Syllable("ты", "", 50),
    Syllable("ть", "", 96),
    Syllable("хо", "", 47),
    Syllable("ху", "", 13),
    Syllable("ца", "", 12),
    Syllable("це", "", 19),
    Syllable("ча", "", 28),
    Syllable("че", "", 51),
    Syllable("чи", "", 40),
    Syllable("ша", "", 17),
    Syllable("ше", "", 27),
    Syllable("ши", "", 31),
    Syllable("шь", "", 17),
    Syllable("щё", "", 12),
    Syllable("а", ""),
    Syllable("б", ""),
    Syllable("в", ""),
    Syllable("г", ""),
    Syllable("д", ""),
    Syllable("е", ""),
    Syllable("ж", ""),
    Syllable("з", ""),
    Syllable("и", ""),
    Syllable("й", ""),
    Syllable("к", ""),
    Syllable("л", ""),
    Syllable("м", ""),
    Syllable("н", ""),
    Syllable("о", ""),
    Syllable("п", ""),
    Syllable("р", ""),
    Syllable("с", ""),
    Syllable("т", ""),
    Syllable("у", ""),
    Syllable("х", ""),
    Syllable("ц", ""),
    Syllable("ч", ""),
    Syllable("ш", ""),
    Syllable("щ", ""),
    Syllable("э", ""),
    Syllable("ю", ""),
    Syllable("я", ""),
    Syllable("ё", ""),
)
